# Generated by Django 5.0.6 on 2024-06-20 21:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artwork', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('artist', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
            ],
        ),
    ]
