# Generated by Django 5.0.6 on 2024-06-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_album_artwork_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.CharField(default='temporary_default', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.album'),
        ),
    ]
